### ISSUE TITLE
Parameters: [AWSKeyPairName] do not exist in the template

### ISSUE THREAD

**Issue by mourackb** [deep-security/cloudformation#29]
Using the latest version of "master-rhel.template" under 'cloudformation/templates/rhel path'
The Stack of CloudFormation fails during the following step: 
`
16:49:41 UTC+1200 | CREATE_FAILED | AWS::CloudFormation::Stack | DSDatabaseAbstract | Parameters: [AWSKeyPairName] do not exist in the template
-- | -- | -- | -- | --
`

I would like to know if there are more people facing the same problem

**Comment by trend-scottb** [comment]
I just launched that template and I'm not getting that error. We did add a requirement for the key pair into the DSDatabaseAbstract template with the latest release but the variable is called AWSIKeyPairName in that template. Have you modified any of the templates or are you just launching them as is?

**Comment by mourackb** [comment]
Either way, I`ll be closing this issue since it was not reproducible.
