### ISSUE TITLE
Failed to create stack using 

### ISSUE THREAD

**Issue by Tmorinaga** [deep-security/cloudformation#3]
Thank you for great CloudFormation template.

I tried to build DeepSecurity using a RHEL template, but it failed.
I receive an error message below in the `/tmp/dsmInstallLog`.
```
[ERROR] The Manager Address cannot be blank.  Please enter a hostname, IP or domain name.
```

I added the parameter `AddressAndPortsScreen.ManagerAddress=<local ip address>` to `dsmConfiguration.properties`, installation succeeded.

Isn't the parameter needed?
If not needed, how can I create stack without adding the parameter.

**Comment by 424D57** [comment]
We have found that this can occur when dnshostnames are disabled for the VPC. Normally this parameter is not required but in this scenario the manager installer is sometimes unable to resolve a hostname for itself. v0.5 in progress has a fix for this by adding the ```AddressAndPortsScreen.ManagerAddress=<local_ipv4 from metadata>``` line to ```dsmConfiguration.properties``` in the ```installDSM``` config. Fix is in and tested on the marketplace side; I haven't yet moved it to the RHEL template but should have that completed by next week. The fix on marketplace should be direct portable to current RHEL and looks like this:

                    "installDSM"     : {
                        "commands" : {
                            "0-sethostnameinprops" : {
                                "command" : {
                                    "Fn::Join" : [
                                        "",
                                        [
                                            "echo ",
                                            "\"AddressAndPortsScreen.ManagerAddress=$(curl http://169.254.169.254/latest/meta-data/local-ipv4/)\" >> /etc/cfn/dsmConfiguration.properties"
                                        ]
                                    ]
                                },
                                "ignoreErrors" : "false"
                            },

**Comment by Tmorinaga** [comment]
Enabling DnsHostNames make it work!
Thank you very much!
